# -*- coding: utf-8 -*-
"""Portofolio Bootcamp Data Engineer_Dwi Putri Oktaviani

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiSFvBzsJPCFTiO48kDI5tOCjtg2QBuh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/heart_disease.csv")

df.head()

print("Jumlah baris dan kolom:", df.shape)
print("\nNama kolom:")
print(df.columns)

"""PROBLEM DEFINITION

1. Bagaimana distribusi usia pasien?
2. Apakah terdapat perbedaan risiko penyakit jantung berdasarkan jenis kelamin?
3. Fitur apa yang paling sering muncul pada pasien dengan penyakit jantung?
"""

df.info()

df.describe()

df.dtypes

"""Exploratory Data Analysis"""

# Cek Missing Value
df.isnull().sum()

# Cek Duplikat Data
df.duplicated().sum()

# Distirbusi Usia
plt.figure()
plt.hist(df['age'])
plt.title('Distribusi Usia Pasien')
plt.xlabel('Usia')
plt.ylabel('Jumlah')
plt.show()

# Penyakit Jantung Berdasarkan Jenis Kelamin
plt.figure()
sns.countplot(x='sex', data=df)
plt.title('Distribusi Jenis Kelamin')
plt.show()

# Target Variable (Penyakit Jantung)
plt.figure()
sns.countplot(x='target', data=df)
plt.title('Distribusi Penyakit Jantung')
plt.show()

"""# **Dari data yang di olah di dapatkan:**
1. Mayoritas pasien berada pada rentang usia menengah hingga lanjut.
2. Pasien dengan usia lebih tua cenderung memiliki risiko penyakit jantung lebih tinggi.
3. Distribusi pasien pria lebih banyak dibanding wanita.
4. Data cukup bersih karena tidak memiliki missing value dan duplikasi signifikan.

Heart Disease
"""

# Feature & Target Selection
X = df.drop('target', axis=1)
y = df['target']

print("Shape X:", X.shape)
print("Shape y:", y.shape)

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Data training:", X_train.shape)
print("Data testing :", X_test.shape)

#Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

print("Model berhasil dilatih")

y_pred = model.predict(X_test_scaled)

y_pred[:10]

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

